workflow:
  rules:
    - changes: [ "*.pack.yaml" ]
      when: never
    - when: always

stages:
  - build
  - deploy

build:
  stage: build
  tags: [ tank-runner ]
  image: docker.kubit.dev/docker:20.10
  script:
    - docker build . -t tank-default.r1.kubit.dev/nexus-landing-front:${CI_COMMIT_SHORT_SHA} 
    - docker login tank-default.r1.kubit.dev -u tank-default -p ${CI_REGISTRY_PASSWORD}
    - docker push tank-default.r1.kubit.dev/nexus-landing-front:${CI_COMMIT_SHORT_SHA}
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main"'
      when: on_success


deploy:
  stage: deploy
  image: docker.kubit.dev/curlimages/curl:latest
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main" || $CI_COMMIT_REF_SLUG == "cicd"'
      when: on_success
  needs:
    - build
  interruptible: true
  script:
    - 'curl -X POST -F DOCKER_TAG=${CI_COMMIT_SHORT_SHA} -F token=${KUBIT_WEBHOOK_TOKEN} ${KUBIT_WEBHOOK_URL}'